version: '3.3'

services:
   db:
     build:
       context: .
       dockerfile: Dockerfile.db
     container_name: mysql
     volumes:
       - db_data:/var/lib/mysql
       - /MLP_Automation:/MLP_Automation
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     build:
       context: .
       dockerfile: Dockerfile.wordpress
     container_name: wordpress
     volumes:
       - /MLP_Automation:/MLP_Automation
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}